config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'top#top'
  #root to: "items#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :items, only: [:new, :create, :index, :show, :destroy] do
		resource :item_comments, only: [:create, :destroy]
		resource :favorites, only: [:create, :destroy]
	end
	resources :users


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :item


end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :item_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    validates :bike_name, presence: true
    validates :image, presence: true
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord

    belongs_to :user
    belongs_to :item
    validates :comment, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	attachment :profile_image

	has_many :items, dependent: :destroy
	has_many :item_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :name, presence: true
  	validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def create
        @item = Item.find(params[:item_id])
        @favorite = current_user.favorites.new(item_id: @item.id)
        @favorite.save

    end
    def destroy
        @item = Item.find(params[:item_id])
        @favorite = current_user.favorites.find_by(item_id: @item.id)
        @favorite.destroy
    end


end

app/controllers/item_comments_controller.rb
class ItemCommentsController < ApplicationController

	def create
    item = Item.find(params[:item_id])
    comment = current_user.item_comments.new(item_comment_params)
    comment.item_id = item.id
    comment.score = Language.get_data(item_comment_params[:comment])
    comment.save
    redirect_to item_path(item)
	end


private
def item_comment_params
    params.require(:item_comment).permit(
    :user_id,
    :item_id,
    :comment
    	)
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).reverse_order
    @user = current_user
  end

  def show
    begin
      @item = Item.find(params[:id])
      @item_comment = ItemComment.new
    rescue => e
      redirect_to root_path
    end
  end

  def edit
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to items_path
    else
    render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

    private
    def item_params
        params.require(:item).permit(:bike_name, :image, :content)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.page(params[:page]).reverse_order
	end

	def show
		begin
			@user = User.find(params[:id])
			@items = @user.items.page(params[:page]).reverse_order

		rescue => e
			redirect_to root_path
		end

	end
	def edit
		@user = User.find(params[:id])
	end

	def update
        user = User.find(params[:id])
        user.update(user_params)
        redirect_to user_path(user.id)
	end




  private
  def user_params
  	params.require(:user).permit(:name, :email, :car_model, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/item_comments_helper.rb
module ItemCommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorites.html.erb
<% if user_signed_in? %>
  <% if item.favorited_by?(current_user) %>
    <%= link_to item_favorites_path(item),class: "item-text", method: :delete, remote: true do %>
      <div class="link-white"><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
        <%= item.favorites.count %> いいね </div>
      <% end %>
        <% else %>
          <%= link_to item_favorites_path(item),class: "item-text", method: :post, remote: true do %>
            <div class="link-white"><i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= item.favorites.count %> いいね </div>
            <% end %>
              <% end %>
                <% else %>
                  <div class="link-white"><i class="fa fa-heart-o" aria-hidden="true"></i>
                    <%= item.favorites.count %> いいね</div>
                  <% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @item.id %>').html("<%= j(render partial: 'favorites/favorites', locals: {item: @item}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @item.id %>').html("<%= j(render partial: 'favorites/favorites', locals: {item: @item}) %>");

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div class="item-text">
  <div class="text-center">
    <div class="top-content">
      <h1>Gallery</h1>
      <div class="bar"></div>
    </div>
  </div>
  <div class="text-center">
    <% @items.each do |item| %>
      <div class="top-content">
        <h3>
          <%= link_to item.bike_name ,item_path(item.id),class: "white-text" %>
        </h3>
        <div class="bar"></div>
        <%= attachment_image_tag item, :image, size: "500x450", format: 'jpg',class: "img-thumbnail" %>
          <div class="gallery-text text">
            <p>
              <%=safe_join(item.content.split("\n"),tag(:br))%>
            </p>
            <%= attachment_image_tag item.user, :profile_image, format: 'jpg', class: "img-circle", fallback: "no_image.jpg", size:'75x75' %> By
              <%= link_to item.user.name ,user_path(item.user.id)%><br>
                <%= link_to "#{item.item_comments.count} コメント", item_path(item.id) %>
                  <div id="favorites_buttons_<%= item.id %>">
                    <%= render partial: 'favorites/favorites', locals: {item: item} %>
                  </div>
          </div>
      </div>
      <% end %>
        <div class="top-content">
          <%= paginate @items, class: "paginate white-text" %>
        </div>
  </div>
</div>

app/views/items/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-content">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <div class="section-title-wrapper style-1 v1">
                <h3 class="white-text">画像投稿フォーム</h3>
              </div>
              <%= form_for(@item, url: items_path) do |f| %>
                <% if @item.errors.any? %>
                  <div id="error_explanation">
                    <ul class="white-text">
                      <% @item.errors.full_messages.each do |message| %>
                        <li>
                          <%= message %>
                        </li>
                        <% end %>
                    </ul>
                  </div>
                  <% end %>
                    <div class="row">
                      <div class="col-sm-12">
                        <div class="white-text">
                          <%= f.attachment_field :image %>
                        </div>
                      </div>
                    </div> <br>
                    <div class="row">
                      <div class="col-sm-6">
                        <div class="form-group has-icon"> <label class="control-label sr-only">バイク名</label>
                          <%= f.text_field :bike_name, class:"form-control", placeholder:"バイク名" %> <span class="fa fa-building form-control-icon" aria-hidden="true"></span> </div>
                      </div>
                      <div class="col-sm-6"> </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-12">
                        <%= f.text_area :content, class:"form-control", rows:"3", placeholder:"本文ここに" %>
                      </div>
                    </div> <br>
                    <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                      <% end %> <br> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="top-content">
        <div class="clearfix">
          <div class="clearfix">
            <div class="item-profire-image">
              <%= attachment_image_tag @item.user, :profile_image, size: "60x60", fallback: "no_image.jpg", class: "item-title img-circle"%>
            </div>
            <h4 class="item-title-name"> By
              <%= @item.user.name %>
            </h4>
          </div>
          <h2 class="item-title-bike-name">
            <%= @item.bike_name %>
          </h2> 　 </div>
        <div class="bar-show"></div> <br>
        <%= attachment_image_tag @item, :image, size: "770x450", format: 'jpg',class: "img-thumbnail", fallback: "no_image.jpg"  %>
          <div class="item-text">
            <%= @item.created_at.strftime('%Y/%m/%d') %>
              <div id="favorites_buttons_<%= @item.id %>">
                <%= render partial: 'favorites/favorites', locals: {item: @item} %>
              </div> <i class="fa fa-comment"></i>
              <%= @item.item_comments.count %>件コメント
                <div class="post-content-inner mt-20">
                  <p class="item-content text">
                    <%=safe_join(@item.content.split("\n"),tag(:br))%>
                  </p>
                </div>
                <% if @item.user == current_user %>
                  <%= link_to "投稿を削除", item_path(@item),class: "item-delete", method: :delete %>
                    <% end %>
                      <% if user_signed_in? %>
                        <%= form_for [@item, @item_comment] do |f| %>
                          <div class="row">
                            <div class="col-sm-12">
                              <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                            </div>
                            <%= f.submit "送信する", class: "btn btn-lg btn-base-1 pull-right", style: "margin-right: 15px; margin-top: 8px; color: black;"%>
                          </div>
                          <% end %>
                            <% end %>
                              <div class="comment-list bt style-2" id="comments">
                                <ol>
                                  <% @item.item_comments.each do |item_comment| %>
                                    <li class="comment">
                                      <div class="comment-body bb">
                                        <div class="comment-avatar">
                                          <div class="avatar">
                                            <%= attachment_image_tag item_comment.user, :profile_image, size:"60x60", fallback: "no_image.jpg", class: "img-circle" %>
                                          </div>
                                        </div>
                                        <div class="comment-text">
                                          <div class="comment-author clearfix">
                                            <%=link_to item_comment.user.name,user_path(item_comment.user.id),class: "item-text" %>
                                              <%= item_comment.created_at.strftime('%Y/%m/%d') %>
                                          </div>
                                          <div class="comment-entry">
                                            <%= item_comment.comment %>
                                              <div id="star-<%= item_comment.id %>"> <label>コメント評価</label>
                                                <%= hidden_field :star, id: :item_comment_score %>
                                              </div>
                                              <script>
                                                $('#star-<%= item_comment.id %>').raty({
                                                        size     : 36,
                                                        starOff:  '<%= asset_path('star-off.png') %>',
                                                        starOn : '<%= asset_path('star-on.png') %>',
                                                        starHalf: '<%= asset_path('star-half.png') %>',
                                                        half: true,
                                                        readOnly: true,
                                                        score: '<%= 5*(item_comment.score + 1 ) / 2 %>'
                                                      });
                                              </script>
                                          </div>
                                        </div>
                                      </div>
                                    </li>
                                    <% end %>
                                </ol>
                              </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="https://kit.fontawesome.com/040a483df4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <title>bike</title>
</head>
<body>
  <header id="header">
    <nav class="navbar" role="navigation" id="slide-nav">
      <div class="container relative">
        <div class="navbar-header">
          <%= link_to "M's Bike", root_path, class: "logo" %>
        </div>
        <div id="slidemenu">
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
            <% if user_signed_in? %>
              <li>
                <%= link_to " ホーム", user_path(current_user), class: "menu"%>
              </li>
              <li>
                <%= link_to " 投稿一覧", items_path, class: "menu" %>
              </li>
              <li>
                <%= link_to " 新規投稿", new_item_path, class: "menu" %>
              </li>
              <li>
                <%= link_to " ライダーズ", users_path, class: "menu" %>
              </li>
              <li>
                <%= link_to "マイページ", user_path(current_user.id), class: "menu" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menu" %>
              </li>
              <% else %>
                <li>
                  <%= link_to " ホーム", root_path, class: "menu"%>
                </li>
                <li>
                  <%= link_to " 投稿一覧", items_path, class: "menu" %>
                </li>
                <li>
                  <%= link_to " ライダーズ", users_path, class: "menu" %>
                </li>
                <li>
                  <%= link_to "新規登録", new_user_registration_path, class: "menu" %>
                </li>
                <li>
                  <%= link_to "ログイン", new_user_session_path, class: "menu"  %>
                </li>
                <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container header-margin">
    <%= yield %>
  </div>
</body>
</html>

app/views/top/top.html.erb
<div class="text-center">
	<h2><font color="white">M's Bike</font></h2>
	<h3><font color="white">Post your custom bike.And have fun. etemally...</font></h3>
	<%= image_tag 'bike.jpg', :size =>'800x480',class: "img-thumbnail" %>



	<div class="top-content">
		<div class="text-left">
			<h1>　Concept</h1>
		</div>
		<div class="top-text">
			M's Bike では<br>
			皆様のご自慢のアメリカンバイクを投稿していただき<br>
			他のバイクをご自身のカスタムの参考にしてもらうなど<br>
			皆様で作り上げていていただく<br>
			コミュニティサイトです。<br>
			自分でカスタムしたものを見てもらうのは<br>
			気持ちが良いものですね。<br>
			皆様からの素敵なカスタムバイクの投稿<br>
			心よりお待ちしております。<br>
			気に入った投稿がありましたら<br>
			コメントを送ってみましょう。<br>
			<div class="text-left">
				<h1>　Gallery</h1>
			</div>
		</div>


				<%= image_tag 'bike6.jpg', :size =>'240x180',class: "img-thumbnail" %>
				<%= image_tag 'bike7.jpg', :size =>'240x240',class: "img-thumbnail" %>
				<br>
				<%= image_tag 'bike4.jpg', :size =>'240x180',class: "img-thumbnail" %>
				<%= image_tag 'bike3.jpg', :size =>'240x180',class: "img-thumbnail" %>


	</div>
</div>

app/views/users/edit.html.erb
<div class="top-content">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="text-center">
        <h3 class="white-text">プロフィール編集</h3>
      </div>
      <div class="form-body">
        <%= form_for(@user) do |f| %>
          <h3 class="white-text">名前</h3>
          <div class="form-group has-icon"> <label class="control-label sr-only" for="inputEmail">Name</label>
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%> <span class="fa fa-user form-control-icon" aria-hidden="true"></span> </div>
          <h3 class="white-text">自己紹介</h3>
          <div class="form-group has-icon"> <label class="control-label sr-only" for="inputEmail">自己紹介</label>
            <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"自己紹介"%> <span class="fa fa-user form-control-icon" aria-hidden="true"></span> </div>
          <div class="form-group has-icon">
            <div class="user-edit-image">
              <%= attachment_image_tag @user, :profile_image, size: "60x60", class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
            </div> <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
          </div>
          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="text-center">
  <div class="top-content">
    <h1 class="white-text">Rider</h1>
    <div class="bar"></div>
  </div>
</div>
<div class="white-text">
  <% @users.each do |user| %>
    <div class="top-content">
      <div class="image-block">
        <div class="image">
          <%= attachment_image_tag user, :profile_image, format: 'jpg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'125x125' %>
        </div>
        <div class="text-center">
          <%= link_to user.name, user, class: "user_#{user.id}" %>
        </div>
      </div>
      <div class="text-center-profile clearfix">
        <%= user.introduction %>
      </div>
    </div>
    <% end %>
    <div class="top-content text-center">
          <%= paginate @users, class: "paginate white-text" %>
        </div>
</div>

app/views/users/show.html.erb
  <div class="top-content clearfix">
    <div class="profile">
      <%= attachment_image_tag @user, :profile_image,format: 'jpg', class: "img-circle", fallback: "no_image.jpg", size:'150x150' %>
    </div>
    <div class="profile">
      <%= @user.name %>
    </div><br>
    <div class="profile text">
      <%= @user.introduction %>
    </div><br>
    <div class="profile">
      <% if @user == current_user %>
        <botton type="botton" class="btn btn-default">
          <%= link_to "プロフィール編集", edit_user_path(@user.id), class: "black-text" %>
            <% end %>
        </botton>
    </div>
  </div>
  <% if @items.present? %>
<div class="text-center">
          <% @items.each do |item| %>
      <div class="top-content">
        <h3>
          <%= link_to item.bike_name ,item_path(item.id),class: "white-text" %>
        </h3>
        <div class="bar"></div>
        <%= attachment_image_tag item, :image, size: "500x450", format: 'jpg',class: "img-thumbnail" %>
          <div class="gallery-text text">
            <p>
              <%=safe_join(item.content.split("\n"),tag(:br))%>
            </p>
                <%= link_to "#{item.item_comments.count} コメント", item_path(item.id) %>
                  <div id="favorites_buttons_<%= item.id %>">
                    <%= render partial: 'favorites/favorites', locals: {item: item} %>
                  </div>
          </div>
      </div>
      <% end %>
              <div class="top-content">
          <%= paginate @items, class: "paginate white-text" %>
        </div>
    </div>
    <% end %>